config/routes.rb
Rails.application.routes.draw do
  resources :clients
  resources :client_submissions
  devise_for :users

  root 'users#index'

end

app/models/client.rb
class Client < ActiveRecord::Base
	has_many :client_submissions
<<<<<<< HEAD
	has_attached_file :logoSmall, styles: { thumb:"100x100"}
	has_attached_file :logoLarge

=======
	has_attached_file :logoLarge
	has_attached_file :logoSmall
	validates_attachment_content_type :logoLarge, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
>>>>>>> add_bourbon
end

app/models/client_submission.rb
class ClientSubmission < ActiveRecord::Base
	
	
	belongs_to :clients
	has_one :client_submission_data
	has_attached_file :csv_file, validate_media_type: false
	do_not_validate_attachment_file_type :csv_file
end

app/models/client_submission_data.rb
class ClientSubmissionData < ActiveRecord::Base

	belongs_to :client_submission 
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable




end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

before_filter :configure_permitted_parameters, if: :devise_controller?

protected
	
	def configure_permitted_parameters
		devise_parameter_sanitizer.for(:sign_up) << :name
		devise_parameter_sanitizer.for(:sign_up) << :client
	end

end

app/controllers/client_submission_data_controller.rb
class ClientSubmissionDataController < ApplicationController

	def show
		@submissions_data = ClientSubmissionData(params[:id])

	end

end

app/controllers/client_submissions_controller.rb
class ClientSubmissionsController < ApplicationController

def index


end

def show
	@submission = ClientSubmission.find(params[:id])
end

def new
	@submission = ClientSubmission.new
end


def create
	@submission = ClientSubmission.new(submission_params)
	@submission.save!
	redirect_to @submission 
end

private

def submission_params
	params.require(:client_submission).permit(:name, :csv_file)
	
end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
<<<<<<< HEAD
  # before_action :set_client, only: [:show, :edit, :update, :destroy]

  # GET /clients
  # GET /clients.json
=======
	
	before_action :set_client, only: [:show, :edit, :update, :destroy]
	
	
	#GET /clients
  	# GET /clients.json
>>>>>>> add_bourbon
  def index
    @clients = Client.all
  end

  # GET /clients/1
  # GET /clients/1.json
  def show
	@client = Client.find(params[:id])
	@client_submissions = @client.client_submissions 
  end

  # GET /clients/new
  def new
    @client = Client.new
  end

  # GET /clients/1/edit
  def edit
  end

  # POST /clients
  # POST /clients.json
  def create
    @client = Client.new(client_params)

    respond_to do |format|
      if @client.save
        format.html { redirect_to @client, notice: 'Client was successfully created.' }
        format.json { render :show, status: :created, location: @client }
      else
        format.html { render :new }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /clients/1
  # PATCH/PUT /clients/1.json
  def update
    respond_to do |format|
      if @client.update(client_params)
        format.html { redirect_to @client, notice: 'Client was successfully updated.' }
        format.json { render :show, status: :ok, location: @client }
      else
        format.html { render :edit }
        format.json { render json: @client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clients/1
  # DELETE /clients/1.json
  def destroy
    @client.destroy
    respond_to do |format|
      format.html { redirect_to clients_url, notice: 'Client was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_client
      @client = Client.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def client_params
<<<<<<< HEAD
      params.require(:client).permit(:client, :logoSmall , :logoLarge )
=======
      params.require(:client).permit(:client, :logoLarge )
>>>>>>> add_bourbon
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
before_action :authenticate_user!

	def index
	@users = User.all
	end


	def show
	end


	def edit
	end


	def create
	end


	def update
	end
		


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/client_submission_data_helper.rb
module ClientSubmissionDataHelper
end

app/helpers/client_submissions_helper.rb
module ClientSubmissionsHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/client_submission_data/show.html.erb
<div>
	<p><%= @submission_data.

</div>

app/views/client_submissions/index.html.erb
require 'csv'

def index 
	<%= form_for @client_submission %>
		<%= form.input :csv, as: :file %>
	<% end %>
end

app/views/client_submissions/new.html.erb
<p> New Client Submission </p>

<%= form_for @submission, url: {action: "create"} do |submission| %>
	<p>Name: <%= submission.text_field :name %></p>
	<p>CSV File:<%= submission.file_field :csv_file %></p>
	<%= submission.submit "Create" %>
<% end %>

app/views/client_submissions/show.html.erb
<div>
<p> Name: <%= @submission.name %></p>
<p> CSV: <%= @submission.csv_file %> </p> 
<p> Debugging <%= @submission %>>
</div>

app/views/clients/_form.html.erb
<%= form_for(@client) do |f| %>
  <% if @client.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@client.errors.count, "error") %> prohibited this client from being saved:</h2>

      <ul>
      <% @client.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/clients/edit.html.erb
<h1>Editing Client</h1>

<%= render 'form' %>

<%= link_to 'Show', @client %> |
<%= link_to 'Back', clients_path %>

app/views/clients/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clients.each do |client| %>
	 <tr>
		<td><%= client.client %>
       		 <td><%= link_to 'Show', client %></td>
       		 <td><%= link_to 'Edit', edit_client_path(client) %></td>
       		 <td><%= link_to 'Destroy', client, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/clients/new.html.erb
<h1>New Client</h1>

<%= form_for @client, url: {action: "create"} do |client| %>
	
	<p>Client: <%= client.text_field :client %></p>
	<p>Logo: <%=  client.file_field :logoLarge  %></p>
	<%= client.submit "Create" %>
<% end %>

	<%= link_to 'Back', clients_path %>

app/views/clients/show.html.erb
<p id="notice"><%= notice %></p>
<<<<<<< HEAD

<div>
<%= @client.logoLarge %>
</div>
=======
<%= @client.client %>
<%= image_tag @client.logoLarge.url %>
>>>>>>> add_bourbon

<% @client_submissions.each do |submission| %>
	<%= submission.name %>
	<%= link_to 'Show Submission', client_submission_path(submission) %>

	
<%end%>	
<%= link_to 'Edit', edit_client_path(@client) %> |
<%= link_to 'Back', clients_path %>
<p><%= link_to 'Create Submission', new_client_submission_path(@client) %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>View</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<nav class="navigation-bar">
	<% if user_signed_in? %>
		<%= link_to "Logout", destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to "Login", new_user_session_path %>
	<% end %>
</nav>
	<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Clients</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
	      <% user.name %>


      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Client', new_client_path %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>